git:
    depth: 3
matrix:
  include:
  - name: "Linux FBX-Conv build"
    language: cpp
    os: linux
    before_install:
      - wget -O premake4.tar.gz http://sourceforge.net/projects/premake/files/Premake/4.4/premake-4.4-beta5-linux.tar.gz/download
      - tar -xf premake4.tar.gz
      - export PATH=$PATH:$PWD
      - wget http://images.autodesk.com/adsk/files/fbx20151_fbxsdk_linux.tar.gz
      - tar -xf fbx20151_fbxsdk_linux.tar.gz
      - chmod +x fbx20151_fbxsdk_linux
      - yes yes | ./fbx20151_fbxsdk_linux fbx-sdk-linux
      - export FBX_SDK_ROOT=$PWD/fbx-sdk-linux
      - export LD_LIBRARY_PATH=$PWD/fbx-sdk-linux/lib/gcc/x64/release/
      - ./generate_makefile
      - cd build/gmake/
    install: true
    script: make config=release